seyon_phpbb3_user:
    template: "SeyonPHPBB3UserBundle::layout.html.twig"
    
    
doctrine:
    orm:
        default_entity_manager:   default
        entity_managers:
            seyon_phpbb3:
                connection:       seyon_phpbb3
                mappings:
                    SeyonPHPBB3UserBundle: ~