services:
    phpbb3_encoder:
        class: Seyon\PHPBB3\UserBundle\Security\Encoder
    seyon_phpbb3_user_provider:
        class: Seyon\PHPBB3\UserBundle\Security\Provider
        arguments: ["@doctrine", 'Seyon\PHPBB3\UserBundle\Entity\User', 'username']
        
    seyon_phpbb3_table_prefix:
        class: Seyon\PHPBB3\UserBundle\EventListener\DoctrineNameListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: seyon_phpbb3 }
